# .goreleaser.yaml
builds:
- main: ./lookup
  binary: 'lookup_v{{ .Version }}_{{ .Os }}_{{ .Arch }}'
  flags:
    - -trimpath
  env:
    - CGO_ENABLED=0
  goos:
    - freebsd
    - windows
    - linux
    - darwin
  goarch:
    - amd64
    - arm
    - arm64
  ignore:
    - goos: windows
      goarch: 'arm64'
