name: Tests
on: [push, pull_request]
jobs:
  test:
    name: Test Linux
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.21
        uses: actions/setup-go@v1
        with:
          go-version: 1.21
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Test
        run: go test -tags test -v ./...
